name = "estelam-platform"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "estelam-platform"

[[d1_databases]]
binding = "DB"
database_name = "estelam"
database_id = "0fcf94f5-abd6-42c7-b09d-407f1a2ee19a"

[[kv_namespaces]]
binding = "KV"
id = "6c2e079bd1294b61bdb9734ea9764641"
preview_id = "bb00a9d856e347538b2c047b6134c576"

[vars]
NEXT_PUBLIC_API_DOMAIN = "https://your-domain.pages.dev"
NEXT_PUBLIC_WEBSITE_DOMAIN = "https://your-domain.pages.dev"
SUPERTOKENS_DASHBOARD_API_KEY = "your-dashboard-api-key"
NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN = "your-mapbox-token"
NEXT_PUBLIC_STREAM_API_KEY = "your-stream-api-key"
STREAM_API_SECRET = "your-stream-api-secret"
NEXT_PUBLIC_CHAT_WORKER_URL = "https://chat-worker.smnshzh.workers.dev"

[build]
command = "npm run build"
cwd = "."

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.json"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.ico", "**/*.woff", "**/*.woff2", "**/*.ttf", "**/*.eot"]